[book]
title = "vJoule doc"
authors = ["Emile Cadorel", "Dimitri Saingre"]
description = "Documentation for vJoule."
src = "src"
language = "en"

[output.html]
additional-css = ["js/custom.css"]
additional-js = ["js/custom.js"]
site-url= "/v0.2/"