[cgroups]
slices = ["vjoule.slice"]

[events]
cgroups = ["PERF_COUNT_HW_CPU_CYCLES", "LLC_MISSES"]
system = []

[sensor]
addr = "0.0.0.0:0"
freq = 1
log-lvl = "info"
log-path = "/etc/vjoule/sensor.log"

